#!/usr/bin/env python

import rospy
import _thread
import threading
import time
import mavros
import subprocess
import re
import os
import shutil
import tf
import math
import multiprocessing
import sys
from datetime import datetime
import json

# Local imports
sys.path.insert(0, '/home/uhdt/ws2_livox/src/mavros/mavros/scripts')

from math import *
from adafruit_servokit import ServoKit
from mavros.utils import *
from mavros_msgs.msg import State, ParamValue, WaypointReached, GlobalPositionTarget, Altitude
from mavros_msgs.srv import ParamSet
from geographic_msgs.msg import GeoPoseStamped
from sensor_msgs.msg import NavSatFix, Imu
from haversine import haversine, Unit
from std_msgs.msg import Float64
import Camera
import shutil
from Search_Area import plan_mission, export_map
from Config import Config


class WaypointMission:
    """
    This class sends position targets to FCU's position controller
    """
    
    
    def __init__(self):
        rospy.init_node('auto_test3')
        mavros.set_namespace()

        # ROS topics to verify state
        self.current_state = State()
        rospy.Subscriber('/mavros/state', State, self.state_callback)

        # Waypoint services
        self.pub = rospy.Publisher('/mavros/setpoint_raw/global', GlobalPositionTarget, queue_size=1)
        while self.pub.get_num_connections() == 0:
            rospy.sleep(.1)

        rospy.Subscriber('/mavros/mission/reached', WaypointReached, self.reached_callback)

        self.setup_search_area_waypoints()
        self.clean()

        # Servos
        #self.SK = ServoKit( channels= 16)

        # Writing file variable
        self.attitude_time = []
        self.deliver_payload_time = []
        self.geotag_time = []
        self.search_area_waypoint_time = []
        self.subprocess_execute_time = []
        self.waypoint_lap_time = []
        self.payload_delivery_time = []

        # Declaring initial variable
        self.pitch = 0.0
        self.roll = 0.0
        self.yaw = 0.0
        self.lat = 0.0
        self.lon = 0.0
        self.alt = 10.0
        self.drone_sensory = [self.pitch, self.roll, self.yaw, self.lat, self.lon, self.alt]
        self.current_waypoint_index = -1
        self.waypoint_reached_event = threading.Event()

        # Lat, Lon, Alt
        # Waypoint lap
        self.waypoints = [
            (21.4000122, -157.7646502, 26),
            (21.4000671, -157.7644846, 26)
        ]

        # Lat, Lon, Alt
        # Keep empty
        self.search_area_waypoints = [

        ]

        # Keep empty
        self.payload_delivery_waypoints = [

        ]

        self.pending_payload = None
        
        self.load_search_area_waypoints()
        print(self.search_area_waypoints)

        # Debugging
        self.test_waypoints = [
            (21.4004180, -157.7646536, 26),
            (21.4001808, -157.7645315, 26),
            (21.4004704, -157.7644336, 26),
            (21.4002619, -157.7643102, 26)
        ]

        self.alt_AD = 26
        # Lat, Lon, Compartment num
        # Leave empty
        self.payload_delivery_waypoints = [

        ]

        # Location hover for manual landing
        self.end_mission_latitude = 21.4003681
        self.end_mission_longitude = -157.7640635
        self.end_mission_altitude = 22

        rospy.loginfo("AUTONOMOUS SCRIPT IS READY!")
        
    def setup_search_area_waypoints(self):
        config = Config("/home/uhdt/UHDT-ODCL-2025/config/config.yaml")
        bound1 = config.params["airdrop"]["boundary"]["bound_1"]
        bound2 = config.params["airdrop"]["boundary"]["bound_2"]
        bound3 = config.params["airdrop"]["boundary"]["bound_3"]
        bound4 = config.params["airdrop"]["boundary"]["bound_4"]
        boundary_coords = [bound1, bound2, bound3, bound4]

        photo_width = config.params["camera"]["search_area_calculator"]["photo_height"]      
        photo_height = config.params["camera"]["search_area_calculator"]["photo_width"]     
        horizontal_fov = config.params["camera"]["search_area_calculator"]["horizontal_fov"]  # degrees
        vertical_fov = config.params["camera"]["search_area_calculator"]["vertical_fov"]     # degrees
        overlap = config.params["camera"]["search_area_calculator"]["overlap"]              # % overlap
        flight_altitude = config.params["camera"]["search_area_calculator"]["flight_altitude"]   # meters
        is_reversed = config.params["camera"]["search_area_calculator"]["is_reversed"]
        boundary_coords = [bound1, bound2, bound3, bound4, bound1]

        (drone_waypoints, angle, rect_centroid, transformer_to_utm, transformer_from_utm,
        ground_width, ground_height, n_cols, n_rows) = plan_mission(
            boundary_coords, photo_width, photo_height, horizontal_fov, vertical_fov, overlap,
            altitude=flight_altitude
        )

        

        export_map("map.html", boundary_coords, drone_waypoints, flight_altitude, angle, rect_centroid, transformer_to_utm, transformer_from_utm, ground_width, ground_height, n_cols, n_rows, is_reversed)
        
    def state_callback(self, msg):
        """
        ROS callback function to return the state of UAS
        """
        self.current_state = msg
        
    def reached_callback(self, msg):
        """
        ROS callback function to return the state of UAS
        """
        rospy.loginfo(f"Waypoint {self.current_waypoint_index} reached")
        self.current_waypoint_index += 1
        self.waypoint_reached_event.set()  # Signal waypoint is reached 


    def is_armed(self):
        """
        Check if the UAS is "ARMED" mode.
        Loops until UAS is ARMED
        """  
        rospy.loginfo("Waiting to be ARMED...")
        while not(self.current_state.armed):
            rospy.loginfo("Waiting to be ARMED...")
            rospy.sleep(1)
            
        rospy.loginfo("ARMED")
        rospy.sleep(1)


    def clean(self):
        '''
        Remake directory for images
        '''
        if os.path.exists("images"):
            shutil.rmtree("images")
        os.mkdir("images")

    def is_guided(self):
        """
        Check if the UAS is "GUIDED" mode.

        Loops until UAS is GUIDED
        """  
        rospy.loginfo("Waiting to be GUIDED")
        while not (self.current_state.mode == "GUIDED"):
            rospy.loginfo("Waiting to be GUIDED...")
            #rospy.loginfo(self.current_state)
            rospy.sleep(1)
        rospy.loginfo("GUIDED")
        rospy.loginfo("!------------------ MISSION STARTING ----------------------!")

    def euler_quaternion(self, quaternion):
        """
        Convert quaternion (x, y, z, w) to Euler angles (roll, pitch, yaw) in degrees.
        """
        euler = tf.transformations.euler_from_quaternion([
            quaternion.x,
            quaternion.y,
            quaternion.z,
            quaternion.w
        ])
        return math.degrees(euler[0]), math.degrees(euler[1]), math.degrees(euler[2])

    def attitude(self):
        """
        Pulls attitude from UAS using MAVROS topics
        Saves information to drone_sensory array
        """
        start = time.time()

        # Get the latest IMU data (orientation)
        imu_msg = rospy.wait_for_message("/mavros/imu/data", Imu, timeout=5)
        self.roll, self.pitch, self.yaw = self.euler_quaternion(imu_msg.orientation)

        # Get the latest GPS data (lat, lon)
        gps_msg = rospy.wait_for_message("/mavros/global_position/global",NavSatFix, timeout=5)
        self.lat, self.lon = gps_msg.latitude, gps_msg.longitude

        rel_alt_msg = rospy.wait_for_message("/mavros/global_position/rel_alt", Float64, timeout=5)
        self.alt = rel_alt_msg.data

        self.drone_sensory = [self.pitch, self.roll, self.yaw, self.lat, self.lon, self.alt]

        rospy.loginfo(f"\nRoll: {self.roll}\nPitch: {self.pitch}\nYaw: {self.yaw}\nlat: {self.lat}\nlon: {self.lon}\naltitude: {self.alt}")
        rospy.loginfo(f"(Attitude Array: {self.drone_sensory}")

        end = time.time()
        difference = end - start
        self.attitude_time.append(difference)
        rospy.loginfo("Drone Sensory data collected")


    def geotag(self, image_name):
        """
        Geotag an image with sensory data.
        Attitude (pitch, roll, yaw) and GPS (latitude, longitude, altitude)

        :param image_name: The filename of the image to geotag.
        :return: None
        """
        
        start = time.time()
        # Geotagging photo with the attitude and GPS coordinate
        self.attitude()
        pyr = ('pitch:' + str(self.drone_sensory[0]) + ' yaw:' + str(self.drone_sensory[2]) + ' roll:' + str(self.drone_sensory[1]))
        print(pyr)
        print( self.drone_sensory[3])
        tag_pyr_command = ('/usr/bin/exiftool','-overwrite_original', '-comment=' + str(pyr), str(image_name))
        tag_lat_command = ('exiftool', '-overwrite_original', '-exif:gpslatitude=' + '\'' + str(self.drone_sensory[3]) + '\'', str(image_name))
        tag_long_command = ('exiftool','-overwrite_original', '-exif:gpslongitude=' + '\'' + str(self.drone_sensory[4]) + '\'', str(image_name))
        tag_alt_command = ('exiftool','-overwrite_original', '-exif:gpsAltitude=' + '\'' + str(self.drone_sensory[5]) + '\'', str(image_name))
        #executing the tag command in ssh

        # DEBUGGING
        '''
        subprocess.run(tag_pyr_command,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        subprocess.run(tag_lat_command,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        subprocess.run(tag_long_command,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        subprocess.run(tag_alt_command,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        '''

        p1 = multiprocessing.Process(target = self.subprocess_execute, args = (tag_pyr_command,))
        p2 = multiprocessing.Process(target = self.subprocess_execute, args = (tag_lat_command,))
        p3 = multiprocessing.Process(target = self.subprocess_execute, args = (tag_long_command,))
        p4 = multiprocessing.Process(target = self.subprocess_execute, args = (tag_alt_command,))
        
        p1.start()
        time.sleep( 1 )
        p2.start()
        time.sleep( 1 )
        p3.start()
        time.sleep( 1 )
        p4.start()
        
        p1.join()
        p2.join()
        p3.join()
        p4.join()
        

        end = time.time()
        difference = end - start
        self.geotag_time.append(difference)

        # Flag ODCL
        flag_name = os.path.splitext(image_name)[0]
        flag_file_name = f"{flag_name}.txt"
        f = open(flag_file_name, "w")
        f.write("")
        f.close()

        return print(f"{image_name} GEOTAGGED")

    def subprocess_execute(self, command):
        """
        Execute a subprocess command with the provided arguments and record the execution time.

        Args:
            command (str): The subprocess command to execute.

        Returns:
            None
        """
        start = time.time()
        result = subprocess.run(command,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        end = time.time()
        difference = end - start
        self.subprocess_execute_time.append(difference)

        print(f"Command executed: {' '.join(command)}")
        print(f"STDOUT: {result.stdout}")
        print(f"STDERR: {result.stderr}")

        if result.returncode != 0:
            rospy.logerr(f"Subprocess command failed: {result.stderr}")
        else:
            rospy.loginfo(f"Subprocess command successful: {result.stdout}")
        
    def RTL_stat( self ):
        """
        Check if the UAS is in "Return to Launch" mode.

        Returns:
            bool: True if the UAS is in RTL mode, False otherwise.
        """

        if self.current_state.mode == "RTL":
            return True
        return False
    
    def gpio_servo_command( self, servo_x, angle ):
        """
        Triggers servo using i2c protocol using adafruit_servokit library
        servo_x: servo number
        angle: angle of the servo (0 to close, 180 to open)
        """
        print( "Dropping Payload" )
        self.SK.servo[ servo_x ].angle = angle
        time.sleep( 1 )
        print( "Dropped Payload" )

    def download_payload_coord( self, file_name ):
        '''
        Parse through ODCL file
        Save onto payload_delivery_waypoints[]
        '''

        num_payloads = None
        
        with open( file_name, 'r' ) as file:
            for line in file:
                # Scan file each line
                latitude_match = re.search( r"Latitude of payload (\w+): (-?\d+\.\d+)", line )
                longitude_match = re.search( r"Longitude of payload (\w+): (-?\d+\.\d+)", line)
                payloads_match = re.search( r"Number of payloads to drop: (\d+)", line )

                # Save the waypoints onto an array
                if latitude_match:
                    print( "Latitude match found:", latitude_match.group() )
                    latitude = float( latitude_match.group(2) )
                    self.pending_payload = [latitude]
                
                if longitude_match:
                    print( "Longitude match found:", longitude_match.group() )
                    longitude = float( longitude_match.group(2) )
                    self.pending_payload.append(longitude)

                if payloads_match:
                    print( "Payloads match found:", payloads_match.group() )
                    num_payloads = int(payloads_match.group(1))
                    self.pending_payload.append(num_payloads)
                    self.payload_delivery_waypoints.append(self.pending_payload)
                    self.pending_payload = None
    
    def load_search_area_waypoints(self):
        '''
        Load waypoints from JSON file
        '''
        with open ("/home/uhdt/ws2_livox/waypoints.json") as f:
            self.search_area_waypoints = json.load(f)["search_waypoints"]


    def deliver_payload_command(self):
        '''
        Deliver payloads based on ODCL
        Do waypoint lap after every delivery
        '''
        file_path = '/home/uhdt/ws2_livox/ip_waypoints/test.txt'

        while not os.path.exists( file_path ):
            print( "Waiting for file" )
            time.sleep( 1 )

        self.download_payload_coord( file_path )
        time.sleep( 5 )

        print( "Starting Payload Delivery Mission" )

        payloads_dropped = 0

        for i, (lat, lon, drops) in enumerate(self.payload_delivery_waypoints):
             
            if (drops != 0):
                for j in range(drops):
                    self.waypoint_reached_event.clear()  # Reset the event
                    print( f"Heading to payload #{payloads_dropped}" )
                    self.send_global_position_target(lat, lon, self.alt_AD)

                    rospy.loginfo(f"Waiting for waypoint to be reached...")
                    self.waypoint_reached_event.wait()

                    time.sleep( 2 )

                    self.gpio_servo_command( payloads_dropped, 180 )
                    print("dropped payload")
                    print( f"Payload #{payloads_dropped} Delivered" )
                    payloads_dropped += 1

                    time.sleep( 25 )

                    if payloads_dropped <= 3:

                        print( "Performing Waypoint Lap" )
                        self.waypoint_lap()
                        print( "Waypoint Lap completed " )
            else:
                print("No drops")
                print("Skipped delivery waypoint")

        print( "Payload Delivery Mission Completed" )

    def set_servos(self, position):
        '''
        Set all servos given position
        position = int
        '''
        if (position == 0):
            self.gpio_servo_command( 0, 0 )
            self.gpio_servo_command( 1, 0 )
            self.gpio_servo_command( 2, 0 )
            self.gpio_servo_command( 3, 0 )

        if (position == 180):
            self.gpio_servo_command( 0, 180 )
            self.gpio_servo_command( 1, 180 )
            self.gpio_servo_command( 2, 180 )
            self.gpio_servo_command( 3, 180 )

        rospy.loginfo("Finished Setting Servos")

    def send_global_position_target(self, lat, lon, alt):
        '''
        Compile waypoint message and publish to topic
        '''
        msg = GlobalPositionTarget()
        msg.header.stamp = rospy.Time.now()
        msg.coordinate_frame = 6
        msg.type_mask = 4088

        msg.latitude = lat  # Latitude
        msg.longitude = lon  # Longitude
        msg.altitude = alt  # Altitude

        self.pub.publish(msg)
        rospy.loginfo("Sent Waypoint")

    def waypoint_lap(self):
        '''
        Following coordinates from waypoints[] array
        '''

        start = time.time()

        rospy.loginfo("=====Waypoint Lap Starting!=====")
        for i, (lat, lon, alt) in enumerate(self.waypoints):
            self.waypoint_reached_event.clear()  # Reset the event
            rospy.loginfo(f"Sending Waypoint {i}")
            self.send_global_position_target(lat, lon, alt)

            # Wait until the drone reaches this waypoint
            rospy.loginfo(f"Waiting for waypoint {i} to be reached...")
            self.waypoint_reached_event.wait()
        
        end = time.time()
        difference = end - start
        self.waypoint_lap_time.append(difference)
            
        rospy.loginfo("Waypoint Lap Completed!")

    def waypoint_test(self):
        '''
        Sandbox test anything that needs waypoints
        '''
        rospy.loginfo("=====Waypoint Lap Starting!=====")
        for i, (lat, lon, alt) in enumerate(self.test_waypoints):
            self.waypoint_reached_event.clear()  # Reset the event
            rospy.loginfo(f"Sending Waypoint {i}")
            self.send_global_position_target(lat, lon, alt)

            # Wait until the drone reaches this waypoint
            rospy.loginfo(f"Waiting for waypoint {i} to be reached...")
            self.waypoint_reached_event.wait()

            time.sleep(2)
            self.gpio_servo_command(i, 0 )
            time.sleep(25)

    def search_area_command(self):
        """
        Define a search area waypoint
        Start ODCL script
        Use waypoint_reached() function to determine if the UAS arrived at location
        Collect UAS attitude data, trigger camera and geotag image

        :return: None
        """
        start = time.time()
        rospy.loginfo('--Now conducting the search area--')
        Camera.initialize(Camera.default)

        counter = 0
        odcl_command = ("/home/uhdt/ws2_livox/odcl.sh")
    
        p1 = multiprocessing.Process(target = self.subprocess_execute, args = (odcl_command,))
        p1.start()
        print(self.search_area_waypoints)

        for i, (lat, lon, alt) in enumerate(self.search_area_waypoints):

            self.waypoint_reached_event.clear()  # Reset the event

            rospy.loginfo(f"Sending Waypoint {i}")
            rospy.loginfo(f"Lat: {lat}, Lon: {lon}, Alt: {alt}")

            self.send_global_position_target(lat, lon, alt)

            # Wait until the drone reaches this waypoint
            rospy.loginfo(f"Waiting for waypoint {i} to be reached...")
            self.waypoint_reached_event.wait()

            rospy.loginfo(f"DONE WITH SEARCH AREA WAYPOINT {i}")
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            image_filepath = os.path.join("images", f"{counter}.jpg")
        
            Camera.trigger(image_filepath)
            time.sleep(4)

            mission.geotag(image_filepath)
            counter += 1
            rospy.loginfo("Triggered Camera")
            
        end = time.time()
        difference = end - start
        self.search_area_waypoint_time.append(difference)

        return print("UAS COMPLETED SEARCH THE AREA")

    def end_mission( self ):

        self.waypoint_reached_event.clear()
        self.send_global_position_target(self.end_mission_latitude, self.end_mission_longitude, self.end_mission_altitude)
        self.waypoint_reached_event.wait()
        rospy.loginfo("End Mission Waypoint Reached")

    def set_param(self, param_name, param_value):
        '''
        Set Ardupilot parameters with parameter name and value
        '''
        rospy.wait_for_service('/mavros/param/set')
        set_param_service = rospy.ServiceProxy('/mavros/param/set', ParamSet)

        param = ParamValue()
        param.integer = int(param_value)
        param.real = float(param_value)

        response = set_param_service(param_name, param)
        if response.success:
            rospy.loginfo(f"Sucessfully set Parameter {param_name} to {param_value}")
        else:
            rospy.loginfo(f"Failed to set parameter {param_name}")

    def sum(self, arr):
        """
        Calculate the sum of values in the input array.

        Args:
            arr (list): List of numeric values to be summed.

        Returns:
            float: The sum of values in the input list.
        """
        sum = 0
        for value in arr:
            sum += value
        return sum
    
    def avg(self, arr):
        """
        Calculate the average of values in the input array.

        Args:
            arr (list): List of numeric values to calculate the average from.

        Returns:
            float: The average of values in the input list.
        """
        if len(arr) == 0:
                return 0  # Avoid division by zero for an empty array

        total = sum(arr)
        average = total / len(arr)
        return average

    def export(self):
        """
        Export, Calculate and record the average and sum of execution times for various methods.

        Returns:
            None
        """
        #average calculation
        avg_attitude = self.avg(self.attitude_time)
        avg_geotag = self.avg(self.geotag_time)
        avg_search_area_waypoint = self.avg(self.search_area_waypoint_time)
        avg_subprocess_execute = self.avg(self.subprocess_execute_time)
        avg_waypoint_lap = self.avg(self.waypoint_lap_time)
        avg_payload_delivery_time = self.avg(self.payload_delivery_time)

        #sum calcualtion
        sum_attitude = self.sum(self.attitude_time)
        sum_geotag = self.sum(self.geotag_time)
        sum_search_area_waypoint = self.sum(self.search_area_waypoint_time)
        sum_subprocess_execute = self.sum(self.subprocess_execute_time)
        sum_waypoint_lap = self.sum(self.waypoint_lap_time)
        sum_payload_delivery_time = self.sum(self.payload_delivery_time)

            
        data_averages_and_time = [
            ("attitude", self.attitude_time, avg_attitude, sum_attitude),
            ("deliver_payload", self.deliver_payload_time, avg_payload_delivery_time,sum_payload_delivery_time ),
            ("geotag", self.geotag_time, avg_geotag,sum_geotag),
            ("search_area_waypoint", self.search_area_waypoint_time, avg_search_area_waypoint,sum_search_area_waypoint),
            ("subprocess_execute", self.subprocess_execute_time, avg_subprocess_execute,sum_subprocess_execute),
            ("waypoint_lap", self.waypoint_lap_time, avg_waypoint_lap,sum_waypoint_lap),

        ]
        # Edit this later
        with open('Data_log.txt', 'a') as file:
                for data_name, data_values, data_average, data_sum in data_averages_and_time:
                        file.write(f"{data_name}: {data_values}\n")
                        file.write(f"{data_name} average: {data_average} seconds\n")
                        file.write(f"{data_name} sum: {data_sum} seconds\n\n")

    def run_full_mission(self):
        '''
        Runs a full mission with
        Search Area, ODCL, Payload Delivery, Waypoint lap
        '''

        self.is_armed()
        self.is_guided()

        self.search_area_command()

        self.deliver_payload_command()

        self.end_mission()



if __name__ == '__main__':
    print(Camera)
    mission = WaypointMission()
        
    mission.set_param('WPNAV_SPEED', 1000) #cm/s
    mission.set_param('WPNAV_SPEED_DN', 500) #cm/s
    mission.set_param('WPNAV_SPEED_UP', 500) #cm/s
    mission.set_param('GUID_OPTIONS', 64) # NOT CHANGE!!!

    mission.run_full_mission()

    '''
    DEBUGGING
    '''
    #mission.set_servos()

    #mission.waypoint_test()
    #Camera.trigger("2.jpg")
    #mission.geotag("2.jpg")
    
    #Camera.flight_testing(Camera.PRESETS, 2, mission.geotag)

    rospy.loginfo("Mission Completed!")
    rospy.spin()

        

